### ISSUE TITLE
Allow all users to request groups in a DM, not just the commissioner

### ISSUE THREAD

**Issue by Camtendo** [Camtendo/smashleaguebot#2]
To clean up channel spam, let's allow users to DM the bot for certain commands as well

**Comment by 16jmiller** [comment]
@jjstobbe added logic to allow normies to access group standings.

**Comment by 16jmiller** [comment]
We've discussed allowing users to see upcoming matches and/or historical records.

**Comment by Camtendo** [comment]
Fixed in https://github.com/Camtendo/smashleaguebot/commit/5dbbf9ea03a691efd0cc88ea9541d6c73cb43adb
